version: "3.7"

volumes:
    database-volume:

services:
    proxy:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        restart: always
        ports:
            - 3333:80

    car-scraper:
        build:
            context: .
            dockerfile: ./docker/scraper/Dockerfile
        env_file:
            - .env.default
        volumes:
            - .:/usr/src/app
            - /usr/src/app/keys
            - /usr/src/app/frontend
            - /usr/src/app/frontend_old

    frontend:
        build:
            context: ./frontend
            dockerfile: ./../docker/frontend/Dockerfile
        volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/dist

    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret_password
        volumes:
            - database-volume:/var/lib/mysql
            